---
title: "Class Code"
author: "Charlie Nagle"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
library(tidyverse)
library(here)
library(broom)
```

## Winter Chapter 1

this is code from chapter 1 of the winter textbook.

```{r}
numbers <- c(18, 1024, 92, 73, 14)
sum(numbers)
mean(numbers)
sd(numbers) %>% round(digits = 2) # can include 'digits =' but don't need to because r recognizes the order of arguments; round(digits = 2) is the same as round(2)
sd(numbers) %>% round(2)

names <- c("dana", "charlie", "louis", "ari") # store these names as a list; reminder c() stands for concatenate

# read in the data
data_nettle <- read_csv("nettle_1999_climate.csv") # note, winter uses capitalization

# inspect the data
str(data_nettle) # base R inspect the dataframe
glimpse(data_nettle) # tidyverse inspect the dataframe

# make a plot of population by area
# note 
ggplot(data = data_nettle, aes(x = Population, y = Area)) +
  geom_point(
    color = "blue",
    shape = 21,
    size = 3
  )
# make a histogram of values
ggplot(data_nettle, aes(Population)) +
  geom_histogram()
```

##  Winter Chapter 2

### 2.11.3

```{r}
data_nettle <- read_csv(here("Data", "nettle_1999_climate.csv"))
# show data only for Benin
data_nettle %>%
  filter(Country == "Benin")
# show data from Benin and Zaire
data_nettle %>%
  filter(Country %in% c("Benin", "Zaire"))
# show only Langs column
data_nettle %>%
  select(Langs)
# show Langs data for Benin
data_nettle %>%
  filter(Country == "Benin") %>%
  select(Langs)
# show data for Population to MGS columns for Benin
data_nettle %>%
  filter(Country == "Benin") %>%
  select(Population:MGS)
# return rows where Langs > 200
data_nettle %>%
  filter(Langs > 200)
# return rows where Langs > 200 and Population < median(Population)
data_nettle %>%
  filter(Langs > 200,
         Population < median(Population))
```

### 2.11.4

```{r}
data_nettle %>%
  filter(Population < 4) %>%
  mutate(
   MGS_cat = ifelse(MGS < 6, "dry", "fertile") 
  ) %>%
  group_by(MGS_cat) %>%
  summarize(LangSum = sum(Langs))

# using case_when
data_nettle %>%
  filter(Population < 4) %>%
  mutate(
    MGS_cat = case_when(
      MGS <  6 ~ "dry",
      MGS >= 6 ~ "fertile",
      .unmatched = "error"
    )
  ) %>%
  group_by(MGS_cat) %>%
  summarize(LangSum = sum(Langs))

# example
data_nettle %>%
  filter(Population < 4) %>%
  mutate(
    MGS_cat = case_when(
      MGS <  4 ~ "very dry",
      MGS <  6 ~ "dry",
      MGS <  8 ~ "fertile",
      MGS >= 8 ~ "very fertile",
      .unmatched = "error"
    ),
    MGS_cat = fct_relevel(MGS_cat, "very dry", "dry", "fertile", "very fertile")
  ) %>%
  group_by(MGS_cat) %>%
  summarize(LangSum = sum(Langs))

# sanity check: does case_when operate the way i think it does
data_nettle %>%
  mutate(
    MGS_cat = case_when(
      MGS <  4 ~ "very dry",
      MGS <  6 ~ "dry",
      MGS <  8 ~ "fertile",
      MGS >= 8 ~ "very fertile",
      .unmatched = "error")
    ) %>%
  group_by(MGS_cat) %>%
  count()

# get descriptive statistics for the smallpopulation data
data_nettle %>%
  filter(Population < 4) %>%
  mutate(
    MGS_cat = case_when(
      MGS <  4 ~ "very dry",
      MGS <  6 ~ "dry",
      MGS <  8 ~ "fertile",
      MGS >= 8 ~ "very fertile",
      .unmatched = "error"
    ),
    MGS_cat = fct_relevel(MGS_cat, "very dry", "dry", "fertile", "very fertile")
  ) %>%
  group_by(MGS_cat) %>%
  summarize(mean = mean(Langs) %>% round(2),
            sd = sd(Langs) %>% round(2),
            min = min(Langs),
            max = max(Langs))
```

## Winter Chapter 3

```{r}
# generate and plot a normal distribution
rnorm(50) %>%
  hist() # base r

# non-base r version
rnorm(50) %>%
  as.data.frame() %>%      # make a data frame
  rename(score = 1) %>%    # rename the variable
  ggplot(aes(x = score)) + # make the plot
  geom_histogram()

# set the mean and sd
rnorm(50, 71.82, 10.42) %>%
  hist() 

# with ggplot
rnorm(50, 71.82, 10.42) %>%
  as.data.frame() %>%
  rename(score = 1) %>%
  ggplot(aes(x = score)) +
  geom_histogram(color = "black", fill = "white")

# with 12 participants
rnorm(12, 71.82, 10.42) %>%
  as.data.frame() %>%
  rename(score = 1) %>%
  ggplot(aes(x = score)) +
  geom_histogram(color = "black", fill = "white")
# with 1200
rnorm(1200, 71.82, 10.42) %>%
  as.data.frame() %>%
  rename(score = 1) %>%
  ggplot(aes(x = score)) +
  geom_histogram(color = "black", fill = "white")

# how would we screen / filter scores > 100 and < 0
rnorm(1200, 71.82, 10.42) %>%
  as.data.frame() %>%
  rename(score = 1) %>%
  filter(score <= 100) %>%
  ggplot(aes(x = score)) +
  geom_histogram(color = "black", fill = "white")

# convert to sds
rnorm(1200, 71.82, 10.42) %>%
  as.data.frame() %>%
  rename(score = 1) %>%
  filter(score <= 100) %>%
  mutate(
    score.z = scale(score) # take the z score (standardize)
  ) %>%
  ggplot(aes(x = score.z)) +
  geom_histogram(color = "black", fill = "white")
```

### Emotional valence

```{r}
# read the data
data_war <- read_csv(here("Data", "warriner_2013_emotional_valence.csv"))

# look at the variables
glimpse(data_war)

# take the range using base r
range(data_war$Val)

# look up the word with the minimum and maximum valence (return the row matching those conditions)
data_war %>%
  filter(Val == min(Val) | Val == max(Val))

# what else could we do with the data
```

### 3.10.1

```{r}
data_war %>%
  ggplot(aes(x = Val)) +
  geom_histogram(color = "black", fill = "white") +
  geom_vline(xintercept = mean(data_war$Val), size = 2) +
  geom_vline(xintercept = mean(data_war$Val) - sd(data_war$Val), linetype = "dashed") +
  geom_vline(xintercept = mean(data_war$Val) + sd(data_war$Val), linetype = "dashed") +
  geom_vline(xintercept = mean(data_war$Val) - 2*sd(data_war$Val), linetype = "dashed") +
  geom_vline(xintercept = mean(data_war$Val) + 2*sd(data_war$Val), linetype = "dashed") +
  theme_minimal()
```

### 3.10.2

```{r}
data_war %>%
  ggplot(aes(x = Val)) +
  geom_density(color = "black", fill = "white") +
  geom_vline(xintercept = mean(data_war$Val), size = 2) +
  geom_vline(xintercept = mean(data_war$Val) - sd(data_war$Val), linetype = "dashed") +
  geom_vline(xintercept = mean(data_war$Val) + sd(data_war$Val), linetype = "dashed") +
  geom_vline(xintercept = mean(data_war$Val) - 2*sd(data_war$Val), linetype = "dashed") +
  geom_vline(xintercept = mean(data_war$Val) + 2*sd(data_war$Val), linetype = "dashed") +
  theme_minimal()
```

### Boxplots

```{r}
# valence of words a vs p
library(stringr)
data_war %>%
  mutate(
    word_type = case_when(
      str_detect(Word, "^a") ~ "a",
      str_detect(Word, "^p") ~ "p",
      .default = "error"
    )
  ) %>%
  filter(word_type != "error") %>%
  ggplot(aes(x = word_type, y = Val)) +
  geom_boxplot() +
  theme_minimal()

# creating a valence factor with levels low, medium, high
data_war %>%
  mutate(
    word_type = case_when(
      Val < 3 ~ "low",
      Val < 7 ~ "medium",
      Val >= 7 ~ "high",
      .default = "error"),
    word_type = fct_relevel(word_type, "low", "medium", "high")
  ) %>%
  ggplot(aes(x = word_type, y = Val)) +
  geom_boxplot() +
  theme_minimal()
```

## Winter Chapter 4

```{r}
# generate predictor
x <- rnorm(50)
# generate outcome
y <- 10 + 3*x
# generate error
error <- rnorm(50)
# remake outcome
y <- 10 + 3*x + error

# make this into a dataframe
df <- tibble(
  predictor = x,
  outcome = y
  )

# fit a regression and get a tidy output
fm <- lm(outcome ~ predictor, df)
tidy(fm)
# rounding to three decimals
tidy(fm) %>%
  mutate(
    across(
      where(is.numeric), ~ round(.x, 3)
    )
  )
# add predicted values to df (predictions for actual observations)
df <- df %>%
  mutate(
    fitted = predict(fm),
    residual = fitted - outcome
  )
# create a new set of values and predict
df_prediction <- tibble(predictor = seq(-3, 3, 0.1))
df_prediction$predicted <- predict(fm, newdata = df_prediction)

# make a plot
ggplot(df, aes(predictor, outcome)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_minimal()
```

### 4.10.1

```{r}
# read, convert variables to lowercase, and inspect the data
data_elp <- read_csv(here("Data", "ELP_frequency.csv")) %>%
  rename_with(tolower)
glimpse(data_elp)
# make log variable
data_elp <- data_elp %>%
  mutate(
    freq.log = log10(freq)
  )
# fit and inspect the model
fm <- lm(rt ~ freq.log, data_elp)
tidy(fm) %>%
  mutate(
    across(
      where(is.numeric), ~ round(.x, 3)
    )
  )
# make a plot
ggplot(data_elp, aes(freq.log, rt)) +
  geom_point() +
  geom_smooth(method = "lm") +
  geom_hline(yintercept = mean(data_elp$rt)) +
  theme_minimal()
# how would we label the words?
# how would we fix the resulting plot?
# (prevent words from being cut off)
# (show words on top of the fit line)

# updated plot
ggplot(data_elp, aes(freq.log, rt, label = word)) +
  geom_smooth(method = "lm") +
  geom_label() +
  geom_hline(yintercept = mean(data_elp$rt)) +
  scale_x_continuous(limits = c(0, 5)) +
  labs(
    x = "Log10(Frequency)",
    y = "RT"
  ) + 
  theme_minimal()
```

### 4.10.2

```{r}
fm <- lm(outcome ~ predictor, df)
fm_null <- lm(outcome ~ 1, df)

# compute r2
1 - sum((residuals(fm)^2)) / sum((residuals(fm_null)^2))
glance(fm)
```

## Data Simulation

```{r}
# simple version with 20 participants and 10 items
# participants
participants <- 20
# items
items <- 10
# groups
groups <- 2
# make a grid (cross everything)
df <- expand.grid(
  participant = factor(1:participants),
  item = factor(1:items),
  group = factor(1:groups)
) %>%
  mutate(
    group = ifelse(group == 1, "a", "b"),
    group.numeric = ifelse(group == "a", 0, 1),
    rt_a = rnorm(400, 500, 100),
    rt_b = rnorm(400, 500, 100),
    rt_b = rt_b - rnorm(400, 10, 10)
    )
df %>%
  ggplot(aes(x = rt, fill = group)) +
  geom_histogram()
min(df$rt)
# how can we simulate different values using rnorm()? done
# how do we add group a vs b? done
# how can we simulate b responds more quickly than a? (1.2x more quickly)
```

## Winter Chapter 5

```{r}
# read the data, convert to lowercase, make the log variables, all in one step
data_elp <- read_csv(here("Data", "ELP_frequency.csv")) %>%
  rename_with(tolower) %>%
  mutate(
    freq_log10 = log10(freq),
    rt_log = log(rt)
    )

# make the plots
data_elp %>%
  ggplot(aes(x = freq, y = rt_log, label = word)) +
  geom_text() +
  geom_smooth(method = "lm") +
  theme_minimal()
data_elp %>%
  ggplot(aes(x = freq_log10, y = rt_log, label = word)) +
  geom_text() +
  geom_smooth(method = "lm") +
  theme_minimal()

# make and inspect model
fm_elp1 <- lm(rt_log ~ freq_log10, data = data_elp)
tidy(fm_elp1) %>%
  mutate(
    across(
      where(is.numeric), ~ round(.x, 3)
    )
  )

# store the full intercept and slope using winter's code
b0 <- tidy(fm_elp1)$estimate[1]
b1 <- tidy(fm_elp1)$estimate[2]
# can write a simple function to compute
frequency <- function(x) {
  b0 + b1 * x
}
frequency(1) # 10
frequency(3) # 1000
# predicts on the log scale
# update the function to output raw rt
frequency <- function(x) {
  exp(b0 + b1 * x)
}
frequency(1) # 10
frequency(3) # 1000

# how can we use predict to get the values?
# get predictions for observed values of frequency
data_elp <- data_elp %>%
  mutate(
    fitted = predict(fm_elp1)
  )
# get predictions for specific values
predict(fm_elp1, newdata = data.frame(freq_log10 = c(1, 3, 5))) %>%
  exp()
# make sure to input values based on the predictor's scale
# 1: frequency = 10 (on log10)
# 3: frequency = 1000
# 5: frequency = 100,000
# get predictions for a range of values using seq()
predict(fm_elp1, newdata = data.frame(freq_log10 = seq(1, 3, by = .1))) %>%
  exp() %>%
  round(0) # to get whole numbers, in milliseconds

# create the centered and z-scored variables
data_elp <- data_elp %>%
  mutate(
    freq_log10_c = scale(freq_log10, scale = F),
    freq_log10_z = scale(freq_log10)
  )
# fit the models
fm_elp1_c <- lm(rt_log ~ freq_log10_c, data = data_elp)
fm_elp1_z <- lm(rt_log ~ freq_log10_z, data = data_elp)
tidy(fm_elp1)   %>% dplyr::select(term, estimate)
tidy(fm_elp1_c) %>% dplyr::select(term, estimate)
tidy(fm_elp1_z) %>% dplyr::select(term, estimate)

# get the correlation
data_elp %>%
  select(freq_log10, rt_log) %>%
  cor() %>% round(3)
# suppress the model intercept
lm(scale(rt_log) ~ 0 + freq_log10_z, data_elp) %>%
  tidy() %>%
  select(estimate) %>% round(3)

# next chapter we move to multiple regression:
# y = b0 + b1x + b2x ... + e
# in this chapter, we dealt with frequency
# in the next, we will add word length
# what is the interpretation of the intercept for the following models
# rt ~ frequency + length (frequency = 0 and length = 0, no!)
# rt ~ frequency_c + length_c (frequency = mean(frequency) and length = mean(length))
# rt ~ frequency_c(mean) + length_c(3syllables)
```

